### ISSUE TITLE
I have 136 errors when rebuilding this project

### ISSUE THREAD

**Issue by tupro2002** [MarekLani/EZ-Robot-With-Cognitive-Services#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'AutoPositionActionFrame' could not be found (are you missing a using directive or an assembly reference?)	EZFormApplication	C:\Users\HP\source\repos\ClassLibrary7\EZFormApplication\Autoposition.cs	453	Active

Particularly this error I have 113 errors

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'AutoPosition' does not exist in the namespace 'EZ_B' (are you missing an assembly reference?)	EZFormApplication	C:\Users\HP\source\repos\ClassLibrary7\EZFormApplication\Autoposition.cs	690	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'AutoPositionAction' does not exist in the current context	EZFormApplication	C:\Users\HP\source\repos\ClassLibrary7\EZFormApplication\Autoposition.cs	747	Active

**Comment by MarekLani** [comment]
sorry I did not realize, package restore won't work for EZB.SDK as it is not downloaded from nuget package repo. I included sdk in repo. Please try to clone the project again, restore packages (run rebuild) and get back to me if it is working.

**Comment by tupro2002** [comment]
Please wait for my results next week, if there is an error I will need your help. Thanks very much

**Comment by tupro2002** [comment]
I worked with it all afternoon but there was one thing that the DJ removed SDK code in EZ-builder so I couldn't export my C # code to associate with your code, so I asked if you could use the code. Your Autoposition SDK with my?
One thing I want to ask you for help, when I recover the packages, I get an error like the one below
![error ez](https://user-images.githubusercontent.com/52948164/62220114-b3f58d00-b3d9-11e9-9342-2b7e1d4cd0a3.jpg)

**Comment by MarekLani** [comment]
hello @tupro2002  try Build -> Clean Solution and then Run it. It should work.

**Comment by tupro2002** [comment]
thank you but i think your way of doing it does not solve the problem even though i have restored the package in Restore but it is still ineffective and when i click on the packages ADDreferences then it says error as shown below
![image](https://user-images.githubusercontent.com/52948164/62260986-11bbc080-b43e-11e9-9871-3ab06a78534b.png)

**Comment by tupro2002** [comment]
I fixed the error via Github but when I uploaded the plugin, I got this error, then I tried to retry it many times but still informed
![image](https://user-images.githubusercontent.com/52948164/62295236-cbdf1680-b496-11e9-94db-b7d4456a26d1.png)
![image](https://user-images.githubusercontent.com/52948164/62295269-d7324200-b496-11e9-91d8-1b49287747af.png)
![image](https://user-images.githubusercontent.com/52948164/62295286-e1544080-b496-11e9-98c1-73c849d2578e.png)

**Comment by tupro2002** [comment]
Looking forward to receiving your help to resolve the above error

**Comment by MarekLani** [comment]
This sample is provided as is. After I added EZB.SDK packages, the rest of the packages should be restored and you should be capable to run the application. Sometimes VS produces unexpected errors when restoring packages, however after cloning latest version in this repo and running package restore, cleaning and rebuilding of application, you should be able to run it. I am really not sure what you need the plugin.xml file for.

**Comment by tupro2002** [comment]
What do you mean, the Plugin.xml file is the file to upload the application to the Ez-builder and the first time I mistakenly recorded the dll file and reported the same error. After I corrected and corrected it, now I delete it as you say the build will result in still seeing the plugin file in ez-builder and not seeing your application.

**Comment by MarekLani** [comment]
Sorry but your issues isn't related to any code in this repository. When you have problem building project (and no code error is involved), always try to clean and rebuild solution. My project is not supporting plugins. All custom behavior of the robot was exported to AutoPosition.cs file using EZB application and currently there is no plan to alter it to work with plugins. I suggest you to create basic application with your plugin and copying out pieces of my code with functionality you need, to your solution.

**Comment by tupro2002** [comment]
OH, I resolved when adding Ez-builder.exe and now appear an error in the code:
Severity Code Description Project File Line Suppression State
Error CS0029 Cannot implicitly convert type 'System.Windows.Forms.Panel' to 'System.Windows.Forms.PictureBox' EZFormApplication C: Users HP source reps EZ-Robot-With-Cognitive-Services EZFormApplication Form1.cs 481 Active

**Comment by tupro2002** [comment]
error in line in form1.cs: this.camera.SetPreviewControl = this.Video2P;

**Comment by MarekLani** [comment]
Can you confirm, you are using EZB libraries from this repository? Go to References -> Right click EZ_B and copy the Version here please.

**Comment by tupro2002** [comment]
hello i have utra view you can contact me by email: cuong017a@gmail.com for the ID and password. to solve the problem, it seems more error when i try to fix it

**Comment by tupro2002** [comment]
hello

Vào Th 6, 2 thg 8, 2019 vào lúc 14:37 Marek Lani <notifications@github.com>
đã viết:

**Comment by MarekLani** [comment]
Sorry but I will not connect. In order to make the application work, you need to use exactly the EZB.SDK packages which are in this repository. Otherwise you need to make code changes which will make the project work with newer version of EZB.SDK. This application was made to work with version 2015.7.28.0 . I have tested it myself, that if you clone this repository (as it is now), rebuild, clean and rebuild again, the application will start.

**Comment by tupro2002** [comment]
You can connect ultra view or teamview to preview the code but because there are a lot of error messages even though I have followed your instructions and tried everything, you can help me once because I need the application Your in my project in the upcoming contest

**Comment by tupro2002** [comment]
If you don't want to, it's okay. Excuse me if you feel bothered

**Comment by MarekLani** [comment]
look I am trying to help here, but you are not responding to my questions not confirming you are following my instructions. Connecting to your computer is no go sorry. I can provide support only to code in this repository. Once again please do following steps:

1. Clone this repository (even you did it before), create new folder, clone it there, please note, that there should be no whitespace in the path! This is important.
2. Open the project
3. Click Build -> Rebuild
4. Click Build -> Clean
5. Click Build -> Rebuild
6. Click Start, the application should be running now

You should follow these steps, exactly as stated. If you want, you can do screen recording, so I can confirm, you are doing everything correctly. 

As said, I won't be able to help you with your plugin. This was not part of the project.

**Comment by tupro2002** [comment]
I apologize for bothering you again, but the application failed to load on Ez-builder because I copied the file from github and that's not allowed. Now I start building from the beginning of the project From the beginning, I copied the code from beginning to end to another project and there was an error, is it because I did not connect to Azure service and do I need to do it. not determine "EZ-B"
![image](https://user-images.githubusercontent.com/52948164/62436295-70987700-b769-11e9-83fd-44555bce05bd.png)
![image](https://user-images.githubusercontent.com/52948164/62436335-89089180-b769-11e9-8121-2d96207cff3f.png)
![image](https://user-images.githubusercontent.com/52948164/62436387-accbd780-b769-11e9-9cdc-ac528ec42bfd.png)
![image](https://user-images.githubusercontent.com/52948164/62436396-b3f2e580-b769-11e9-9566-92d79255e19e.png)

**Comment by MarekLani** [comment]
I can only provide support for code as is in this repository. If you decide to use different version of EZB.SDK I cannot offer help. You have to change the code to work with new SDK by yourself. 

When you decided to copy the cognitive services related code to another project, you must copy also CognitiveServicesCommunicators folder and again make changes in the rest of the code to work with new EZB.SDK version.

**Comment by tupro2002** [comment]
Let me ask with LUIS, can I use voice recognition in any language?

**Comment by MarekLani** [comment]
please see list of supported languages here: https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-language-support I will now close this issue as your questions are not related to this repository. For anything related to this project in particular, please open new issue. If you have specific questions about services used within this project, please see official documentation pages.
